### ISSUE TITLE
Error during evaluating model using command evaluate_so3krates_sparse_on 

### ISSUE THREAD

**Issue by AntonCh-G** [general-molecular-simulations/so3lr#10]
Dear Thorben and Adil,
In the current version of SO3LR, this command has not been documented yet. Therefore, I could use it in the wrong way:
```bash
evaluate_so3krates_sparse_on --workdir "path_to/so3lr/so3lr/params" --filepath "path_to/universal_long_nov_ev10.xyz" --max_num_graphs 2 --write_batch_metrics_to "path_to/CSV.csv" --length_unit Angstrom --energy_unit eV
```
Since I got the following error:
```log
WARNING:root:For using TFDSDataLoader please install tensorflow.
WARNING:root:For using TFDSDataLoader please install tensorflow.
WARNING:root:For using TFDSDataLoader please install tensorflow_datasets.
MLFF:root:Loading data from file_list: [PosixPath('/mnt/tier2/project/p200243/tcp_datasets/SO3LR_data/training_data/universal_long_nov_ev10.xyz')] ...
MLFF:root:Load data from /mnt/tier2/project/p200243/tcp_datasets/SO3LR_data/training_data/universal_long_nov_ev10.xyz.
MLFF:root:Calculate short range neighbors within cutoff=4.5 Ang.
MLFF:root:Calculate long-range neighbors within cutoff_lr=100.0 Ang.
385665it [18:46, 342.36it/s]
MLFF:root:... done!
MLFF:root:Restore parameters from /mnt/tier2/project/p200243/acharkin/so3_aulong_fedbj_412_amsgrad_2/checkpoints ...
WARNING:absl:Configured `CheckpointManager` using deprecated legacy API. Please follow the instructions at https://orbax.readthedocs.io/en/latest/api_refactor.html to migrate.
Traceback (most recent call last):
  File "/home/users/u101129/.local/bin/evaluate_so3krates_sparse_on", line 8, in <module>
    sys.exit(evaluate_so3krates_sparse_on())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/u101129/.local/lib/python3.12/site-packages/mlff/CLI/run_evaluation_on.py", line 127, in evaluate_so3krates_sparse_on
    metrics = from_config.run_evaluation(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/u101129/.local/lib/python3.12/site-packages/mlff/config/from_config.py", line 646, in run_evaluation
    raise FileNotFoundError(f'No checkpoint found at {ckpt_dir}.')
FileNotFoundError: No checkpoint found at /mnt/tier2/project/p200243/acharkin/so3_aulong_fedbj_412_amsgrad_2/checkpoints.
```

In practice, I would like to modify a script to output not only error metrics but also to make a prediction on the dataset.

**Comment by tohenkes** [comment]
For the error message: `--workdir` literally takes the working directory of the training not the `params` folder. But that'll help you.

In general, I'd also like to see a more fleshed out evaluation function e.g. saving the predictions and the metrics in a binary to specified location.

**Comment by thorben-frank** [comment]
I will update `evaluate_so3krates_on` soon. For the moment you can maybe check `evaluate-so3lr` as described in the readme or the example for so3lr evaluation in the notebook folder. LMK what you think. 

I do not save metrics to a file at the moment, since choosing a good default for save location is difficult. Maybe one could make this optional, similar to saving the predictions via `--save-predictions-to`?
