### ISSUE TITLE
Impossible to make prediction on dataset with different size molecules using the ASE calculator

### ISSUE THREAD

**Issue by AntonCh-G** [general-molecular-simulations/so3lr#9]
Dear Thorben and Adil,
In the current version of SO3LR, it is impossible to make predictions using the ASE calculator for the dataset, as molecules' sizes vary across the dataset.
I used the universal_long_nov.xyz dataset as an example, but it is valid for any.

```python
import numpy as np
from so3lr import So3lrCalculator
from ase import Atoms
from ase.io import read, write
import sys
from tqdm import tqdm

if __name__ == "__main__":
    path_input = sys.argv[1]
    
    
    traj = read(path_input, index = slice(0,100,1))
    calc = So3lrCalculator(lr_cutoff=5)
    for i,atoms in enumerate(tqdm(traj)):
        a = atoms.copy()
        a.calc = calc   
        forces =a.get_forces()
```
It returns the following error:
```log
Traceback (most recent call last):
  File "/home/users/u101129/SO3LR_eval.py", line 19, in <module>
    forces =a.get_forces()
            ^^^^^^^^^^^^^^
  File "/mnt/tier2/project/p200243/acharkin/env/so3lr_env/lib/python3.12/site-packages/ase/atoms.py", line 812, in get_forces
    forces = self._calc.get_forces(self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/tier2/project/p200243/acharkin/env/so3lr_env/lib/python3.12/site-packages/ase/calculators/abc.py", line 30, in get_forces
    return self.get_property('forces', atoms)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/tier2/project/p200243/acharkin/env/so3lr_env/lib/python3.12/site-packages/ase/calculators/calculator.py", line 538, in get_property
    self.calculate(atoms, [name], system_changes)
  File "/mnt/tier2/project/p200243/acharkin/env/so3lr_env/lib/python3.12/site-packages/mlff/md/calculator_sparse.py", line 276, in calculate
    neighbors = self.spatial_partitioning.update_fn(system.R, self.neighbors, new_cell=cell)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/tier2/project/p200243/acharkin/env/so3lr_env/lib/python3.12/site-packages/glp/neighborlist.py", line 235, in update_fn
    force_update | need_update_fn(neighbors, positions, new_cell),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/tier2/project/p200243/acharkin/env/so3lr_env/lib/python3.12/site-packages/glp/neighborlist.py", line 158, in need_update_fn
    movement = make_squared_distance(new_cell)(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: vmap got inconsistent sizes for array axes to be mapped:
  * one axis had size 18: axis 0 of argument Ra of type float32[18,3];
  * one axis had size 19: axis 0 of argument Rb of type float32[19,3]
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

As reported in another issue here, the fast fix that creates a new neighbor list for each molecule in each iteration is extremely slow, making it impossible to apply it to large datasets.
The script that would allow the evaluation of a model on the dataset and save prediction would be handy.

**Comment by thorben-frank** [comment]
Indeed, you are right. However, this is somewhat intentionally, since an `ASECalculator` is created for a given `ase.Atoms` object which presents one specific entity of a molecular. Therefore, `positions` and `cell` can be updated for the very same molecule, but another molecule corresponds to creating a new `ase.Atoms` object. 

If you want to evaluate on a dataset with different molecules consider using the `base_calculator` of `so3lr`. For its usage you can find an example in the notebook folder, named `evaluate_so3lr_on_dataset.ipynb`. Alternatively, you can also use the CLI `so3lr-evaluate` as desribed in the `README`. LMK if this works for you.
